### ISSUE TITLE
Error on valid JIRA_URL without trailing slash

### ISSUE THREAD

**Issue by klaas-oetken** [habecker/jira-timetracking-cli#7]
Steps to reproduce:

1. set your JIRA_URL to a url without a trailing slash, e.g. http://example.com
2. call book-time with otherwise valid parameters

Actual behavior:
book-time produces an error:
```
XXX-XXXX 2022-11-10T08:00:00.000+0200 0h 30m http://example.comrest/internal/3/issue/XXX-XXX/worklog
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
  File "urllib3/util/connection.py", line 73, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known
```

Expected behavior: 
The time should be booked with no error.

**Comment by habecker** [comment]
Should now be fixed 👍
